# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
imports:
    - { resource : legacy_aliases.yml }
parameters:
    #parameter_name: value

services:
    _defaults:
        autowire: true
        autoconfigure: true

    DealsBundle\Form\DealType:
        arguments: [ "@translator" ]
        tags:
            - { name: form.type }

    DealsBundle\Services\CategorieService:
        arguments: ["@doctrine.orm.entity_manager"]

    DealsBundle\Services\UtilesService:
        arguments:

    DealsBundle\Services\DeleteService:
        arguments: ["@doctrine.orm.entity_manager"]

    DealsBundle\Services\FileService:
        arguments: ["@kernel"]

    DealsBundle\Services\DealService:
        arguments: ["@kernel","@myDealabs.utilesService","@doctrine.orm.entity_manager","@myDealabs.fileService","@myDealabs.voteService"]

    DealsBundle\Services\UserService:
        arguments: []

    DealsBundle\Services\VoteService:
        arguments: ["@doctrine.orm.entity_manager"]


