<?php

namespace DealsBundle\Repository;

use DealsBundle\Entity\Deal;
use DealsBundle\Entity\User;

/**
 * DealVoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DealVoteRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param User $user
     * @param Deal $deal
     * @return bool
     * @throws \Doctrine\ORM\NonUniqueResultException
     * @throws \Exception
     */
    public function findUserDealVote(User $user, Deal $deal)
    {
        $query = $this->createQueryBuilder('dv')
            ->where('dv.user=:userid')
            ->AndWhere('dv.deal=:dealid')
            ->setParameter('userid', $user->getId())
            ->setParameter('dealid', $deal->getId())
            ->getQuery();
        $result = $query->getOneOrNullResult();
        if(!empty($result)) {
            throw new \Exception("L'utilisateur a déjà voté");
        }
        return true;
    }
}
